#!/usr/bin/env node
/**
 * Ginagawa nitong isang self-contained na fonts.css ang mga font files
 * (base64-embedded woff2). Ibig sabihin: walang network call ang renderer,
 * kaya pareho ang output kahit saan mo patakbuhin — sa GitHub Actions,
 * sa laptop mo, o sa server.
 *
 *   npm i @fontsource/cormorant-garamond @fontsource/jost
 *   node build-fonts.js
 */
const fs = require('fs');
const path = require('path');

const FACES = [
  // [package, family, weight, style]
  ['@fontsource/cormorant-garamond', 'Cormorant Garamond', 300, 'normal'],
  ['@fontsource/cormorant-garamond', 'Cormorant Garamond', 400, 'normal'],
  ['@fontsource/cormorant-garamond', 'Cormorant Garamond', 400, 'italic'],
  ['@fontsource/cormorant-garamond', 'Cormorant Garamond', 500, 'normal'],
  ['@fontsource/cormorant-garamond', 'Cormorant Garamond', 600, 'normal'],
  ['@fontsource/jost', 'Jost', 300, 'normal'],
  ['@fontsource/jost', 'Jost', 400, 'normal'],
  ['@fontsource/jost', 'Jost', 500, 'normal'],
  ['@fontsource/jost', 'Jost', 600, 'normal'],
];

const slug = f => f.toLowerCase().replace(/ /g, '-');
let css = '/* Auto-generated by build-fonts.js — huwag i-edit nang manu-mano. */\n';
let total = 0;

for (const [pkg, family, weight, style] of FACES) {
  const file = path.join(
    __dirname, 'node_modules', pkg, 'files',
    `${slug(family)}-latin-${weight}-${style}.woff2`
  );
  if (!fs.existsSync(file)) {
    console.warn(`⚠️  laktawan (wala): ${path.basename(file)}`);
    continue;
  }
  const b64 = fs.readFileSync(file).toString('base64');
  total += b64.length;
  css += `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};`
       + `font-display:block;src:url(data:font/woff2;base64,${b64}) format('woff2')}\n`;
}

const out = path.join(__dirname, 'fonts.css');
fs.writeFileSync(out, css);
console.log(`✅ fonts.css — ${FACES.length} faces, ${(total / 1024).toFixed(0)} KB`);
